[package]
name = "iperf3-json"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde_with = { version = "3.8.3", features = ["time_0_3"] }

[dev-dependencies]
serde_json = "1.0.120"
